image: orai/cosmwasm-gitpod:0.11.7
workspaceLocation: './oraiwasm_scaffold'

tasks:
  - name: init-cargo-file
    init: touch Cargo.toml

vscode:
  extensions:
    - matklad.rust-analyzer
    - oraichain.cosmwasm-ide
